project_id = "inqabwlmvrvqsdrgskju"

[functions.get-training-credentials]
verify_jwt = true

[functions.send-quotation-request]
verify_jwt = false

[functions.analyze-cad]
verify_jwt = false

[functions.calculate-preliminary-quote]
verify_jwt = false

[functions.setup-training-dataset]
verify_jwt = true

[functions.start-training]
verify_jwt = true

[functions.get-training-status]
verify_jwt = true

[functions.cancel-training]
verify_jwt = true